// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvfgU7f0Fq-qeVMpZqbjp1zn3vCXiqaMM',
    appId: '1:512290697530:web:a203ef654896839e07e003',
    messagingSenderId: '512290697530',
    projectId: 'flutterfirebaseintegrati-7006a',
    authDomain: 'flutterfirebaseintegrati-7006a.firebaseapp.com',
    storageBucket: 'flutterfirebaseintegrati-7006a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnT7Z_KHt-7P18CiZHnlv-y4HNsSQnJL4',
    appId: '1:512290697530:android:c1b5bd04d2dfe80607e003',
    messagingSenderId: '512290697530',
    projectId: 'flutterfirebaseintegrati-7006a',
    storageBucket: 'flutterfirebaseintegrati-7006a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0BWR2XIO7RqWLEpb6q9sVg75_lxORzuo',
    appId: '1:512290697530:ios:670e1bad141cfade07e003',
    messagingSenderId: '512290697530',
    projectId: 'flutterfirebaseintegrati-7006a',
    storageBucket: 'flutterfirebaseintegrati-7006a.appspot.com',
    iosClientId: '512290697530-13st4ndl0v07s55o7lag5f8e4hh065ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.galerieImagesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0BWR2XIO7RqWLEpb6q9sVg75_lxORzuo',
    appId: '1:512290697530:ios:670e1bad141cfade07e003',
    messagingSenderId: '512290697530',
    projectId: 'flutterfirebaseintegrati-7006a',
    storageBucket: 'flutterfirebaseintegrati-7006a.appspot.com',
    iosClientId: '512290697530-13st4ndl0v07s55o7lag5f8e4hh065ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.galerieImagesApp',
  );
}
